"""
Thermal properties of UO2 fuel and heat transfer models.

This module provides:
- Temperature-dependent thermal conductivity of UO2 fuel (MATPRO correlation)
- Volumetric heat generation from fission
- Boundary condition models (gap conductance, coolant convection)

Both NumPy and PyTorch implementations are provided.

References
----------
.. [3] Todreas & Kazimi, "Nuclear Systems I" (2012), Ch. 8.
.. [11] Fink, J. K. (2000). "Thermophysical properties of uranium dioxide."
        Journal of Nuclear Materials, 279(1), 1-18.
"""

from __future__ import annotations

from typing import TYPE_CHECKING

import numpy as np

from neutherm.physics.parameters import ThermalParams

if TYPE_CHECKING:
    import torch


# =============================================================================
# UO2 Thermal Conductivity
# =============================================================================
#
# The thermal conductivity of UO2 decreases with temperature in the phonon
# scattering regime (below ~1500 K) and then increases slightly at very high
# temperatures due to electronic/radiative transport. The MATPRO correlation
# captures both regimes:
#
#     k(T) = 1 / (A + B*T) + C * T^3
#             \_____________/   \______/
#              phonon term     radiation term
#
# - The 1/(A + B*T) term: phonon-phonon scattering. As T increases, phonons
#   scatter more frequently, REDUCING thermal conductivity. This is why UO2
#   is a poor conductor at high temperatures — a major challenge in fuel design.
#
# - The C*T^3 term: photon (radiation) transport through the lattice. Only
#   significant above ~2000 K. Follows Stefan-Boltzmann T^4 scaling, but
#   integrated over the grain gives T^3 dependence.
#
# Typical values at reference temperatures:
#   k(300 K)  ≈ 8.0 W/(m·K)   — cold fuel
#   k(700 K)  ≈ 4.0 W/(m·K)   — operating condition
#   k(1500 K) ≈ 2.5 W/(m·K)   — near fuel centerline
#   k(2500 K) ≈ 2.8 W/(m·K)   — radiation term kicks in
#
# These low conductivity values (compare copper: ~400 W/(m·K)) are why
# fuel centerline temperatures can reach 1500-2000 K even though the
# coolant is only at ~580 K.
# =============================================================================


def fuel_conductivity_np(T: np.ndarray, params: ThermalParams) -> np.ndarray:
    """Temperature-dependent thermal conductivity of UO2 fuel (NumPy).

    Uses the MATPRO/Fink correlation:
        k(T) = 1 / (A + B*T) + C * T^3

    Parameters
    ----------
    T : np.ndarray
        Temperature [K].
    params : ThermalParams
        Contains fuel_k_A, fuel_k_B, fuel_k_C coefficients.

    Returns
    -------
    np.ndarray
        Thermal conductivity [W/(m·K)].
    """
    return 1.0 / (params.fuel_k_A + params.fuel_k_B * T) + params.fuel_k_C * T**3


def fuel_conductivity_torch(T: "torch.Tensor", params: ThermalParams) -> "torch.Tensor":
    """Temperature-dependent thermal conductivity of UO2 fuel (PyTorch).

    Differentiable version for use in the PINN loss computation.
    The heat equation residual requires dk/dT, which PyTorch computes
    automatically through this expression.

    Parameters
    ----------
    T : torch.Tensor
        Temperature [K].
    params : ThermalParams
        Contains fuel_k_A, fuel_k_B, fuel_k_C coefficients.

    Returns
    -------
    torch.Tensor
        Thermal conductivity [W/(m·K)].
    """
    # Lazy import — torch only loaded when this function is called
    import torch  # noqa: F811

    return 1.0 / (params.fuel_k_A + params.fuel_k_B * T) + params.fuel_k_C * T**3


# =============================================================================
# Volumetric Heat Generation
# =============================================================================
#
# In a nuclear reactor, heat is generated by fission reactions. Each fission
# event releases ~200 MeV of energy, most of which (~97%) is deposited
# locally in the fuel as kinetic energy of fission fragments.
#
# The volumetric heat generation rate at position r is:
#
#     q'''(r) = κ_f * [Σ_{f,1}(T) * φ_1(r) + Σ_{f,2}(T) * φ_2(r)]
#
# where:
#   κ_f ≈ 3.204 × 10^{-11} J/fission (= 200 MeV converted to Joules)
#   Σ_{f,g} = fission cross section in group g [cm^{-1}]
#   φ_g = neutron flux in group g [n·cm^{-2}·s^{-1}]
#
# This is what couples the neutronics to the thermal problem: more neutrons
# → more fissions → more heat → higher temperature → changed cross sections
# → different neutron distribution. This feedback loop is the core of our
# coupled problem.
#
# Note on units: The cross sections are in cm^{-1} and flux in cm^{-2}s^{-1},
# so q''' comes out in W/cm^3. The thermal solver works in SI (W/m^3), so
# we need a factor of 10^6 when coupling (1 cm^3 = 10^{-6} m^3).
# This conversion is handled in the coupled solver, not here.
# =============================================================================


def heat_generation_np(
    phi1: np.ndarray,
    phi2: np.ndarray,
    sigma_f1: np.ndarray,
    sigma_f2: np.ndarray,
    kappa: float,
) -> np.ndarray:
    """Volumetric heat generation rate from fission (NumPy).

    q'''(r) = κ_f * (Σ_{f,1} * φ_1 + Σ_{f,2} * φ_2)

    Parameters
    ----------
    phi1, phi2 : np.ndarray
        Neutron flux in group 1 (fast) and group 2 (thermal) [n·cm^{-2}·s^{-1}].
    sigma_f1, sigma_f2 : np.ndarray
        Fission cross sections [cm^{-1}].
    kappa : float
        Energy per fission [J/fission]. Default: 3.204e-11 J.

    Returns
    -------
    np.ndarray
        Volumetric heat generation rate [W/cm^3].
    """
    return kappa * (sigma_f1 * phi1 + sigma_f2 * phi2)


def heat_generation_torch(
    phi1: "torch.Tensor",
    phi2: "torch.Tensor",
    sigma_f1: "torch.Tensor",
    sigma_f2: "torch.Tensor",
    kappa: float,
) -> "torch.Tensor":
    """Volumetric heat generation rate from fission (PyTorch).

    Differentiable version for PINN residual computation. Since phi1, phi2
    are outputs of the neural network, and sigma_f1, sigma_f2 depend on T
    (also a network output), gradients flow through this entire expression
    back to the network weights.

    Parameters
    ----------
    phi1, phi2 : torch.Tensor
        Neutron flux in group 1 (fast) and group 2 (thermal).
    sigma_f1, sigma_f2 : torch.Tensor
        Fission cross sections [cm^{-1}].
    kappa : float
        Energy per fission [J/fission].

    Returns
    -------
    torch.Tensor
        Volumetric heat generation rate [W/cm^3].
    """
    return kappa * (sigma_f1 * phi1 + sigma_f2 * phi2)


# =============================================================================
# Boundary Temperature Models
# =============================================================================
#
# The temperature at the fuel surface is determined by the thermal resistance
# chain from the fuel surface → gap → cladding → coolant:
#
#     T_fuel_surface = T_coolant + q'' / h_conv + q'' / h_gap
#
# where:
#   q'' = surface heat flux [W/m²]
#   h_conv = coolant convective HTC [W/(m²·K)] — from Dittus-Boelter
#   h_gap = gap conductance [W/(m²·K)] — depends on gap gas composition,
#           contact pressure, surface roughness
#
# In our 1D model, this provides the outer boundary condition for the
# heat conduction equation.
# =============================================================================


def fuel_surface_temperature(
    q_linear: float,
    params: ThermalParams,
) -> float:
    """Estimate the fuel surface temperature from the linear heat rate.

    This is a simplified estimate for solver initialization. The actual
    boundary condition is computed iteratively in the coupled solver
    using the radial temperature profile.

    Parameters
    ----------
    q_linear : float
        Linear heat rate [W/m].
    params : ThermalParams
        Thermal-hydraulic parameters.

    Returns
    -------
    float
        Estimated fuel surface temperature [K].
    """
    # Approximate thermal resistance chain:
    # T_surface ≈ T_coolant + q'/(2π·R_clad·h_conv) + q'/(2π·R_fuel·h_gap)
    # Using typical PWR dimensions hardcoded here for the estimate.
    # The coupled solver uses exact geometry from the config.
    T_surf = params.T_coolant + q_linear / (2 * np.pi * params.h_conv * 0.00475)
    T_surf += q_linear / (2 * np.pi * params.h_gap * 0.004096)
    return T_surf